### ISSUE TITLE
Use gltf-transform for reading glTF files

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs-indexer#7]
Currently we use custom code for reading glTF json and meshes. However, this implementation is pretty simple and does not support extensions like Draco compression which are becoming common. 

Switching to [gltf-transform](https://gltf-transform.donmccurdy.com/) library will ensure support for a wide range of input.

**Comment by AnaBelgun** [comment]
to finish today

**Comment by na9da** [comment]
[PR here](https://github.com/TerriaJS/terriajs-indexer/pull/8).

Awaiting customer testing.

**Comment by nf-s** [comment]
Fixed bug, so waiting again for testing - person on their side is on leave
